---
title: "p8105_hw3_jl6321.Rmd"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 2

Read and tidy the data. 

```{r Problem2-1}
accel_df = 
  read_csv('./Data/accel_data.csv') %>% 
  pivot_longer( 
    activity.1:activity.1440, 
    names_to = "minute", 
    names_prefix = "activity.", 
    values_to = "activity_counts" 
  ) %>% 
  mutate(if_weekend = (day %in% c('Saturday', 'Sunday'))) %>% 
  relocate(if_weekend, .after = day_id)
```

Variables in this dataset include `r colnames(accel_df)`. There are `r nrow(accel_df)` observations in total. 

Aggregate across minutes for each day and create a table. 

```{r Problem2-2}
accel_aggregate = accel_df %>%
  group_by(week, day) %>%
  summarise(total_activity = sum(activity_counts)) %>%
  pivot_wider(
    names_from = "day",
    values_from = "total_activity"
  ) 
accel_aggregated = accel_aggregate[, c(1, 3, 7, 8, 6, 2, 4, 5)]
accel_aggregated
```

There does not seem to be any apparent trend based on the table besides that the total activities on the 4th and 5th Saturday tend to be low. 

Make a single-panel plot. 

```{r}
accel_df %>% 
  mutate(minute = as.numeric(minute)) %>% 
  group_by(day, minute) %>% 
  summarize(mean_activity_counts = mean(activity_counts)) %>% 
  ggplot(aes(x = minute, y = mean_activity_counts, color = day)) + 
  geom_smooth(se = FALSE) + 
  labs( 
    title = "Average Activity Time Across the Day", 
    x = "Hour", 
    y = "Average Activity Time", 
    caption = "Data from accel.csv dataset") + 
  scale_x_continuous(breaks = c(0:24) * 60, labels = c(0:24))
```

